"use client"
import './globals.css'
import type { Metadata } from 'next'

import {AppShell, Navbar, Header, createStyles, MantineProvider, Flex } from '@mantine/core';
import Link from 'next/link';

const useStyles = createStyles((theme) => ({
  blackbg: {
    backgroundColor: "black",
  },
  linkTitleStyle: {
    color: "white",
    textTransform: "uppercase",
    fontSize: "2em",
    margin: "0 auto"
  },
  linkStyle: {
    color: "white",
    textTransform: "uppercase",
    fontSize: "1em",
  },
}));

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const { classes } = useStyles();
  return (
    <html lang="en">
      <MantineProvider withGlobalStyles withNormalizeCSS>
        <body className={classes.blackbg}>
          <AppShell 
          padding="md"
          navbar={<Navbar className={classes.blackbg} width={{ base: 300 }} p="xs">{
            <Flex direction="column" justify="center" align="center" >
              <Link className={classes.linkStyle} href="/">Home</Link>
              <Link className={classes.linkStyle} href="/posts">Posts</Link>
            </Flex>}
            </Navbar>}
          header={<Header className={classes.blackbg} height={60} p="xs">{
            <Flex>
              <Link href="/" className={classes.linkTitleStyle}>Void GG</Link>
            </Flex>
          }</Header>}
          styles={()=>(
          {
           main:{ backgroudColor: "black"}
          })}
          >
            {children}
          </AppShell>
        </body>
      </MantineProvider>
    </html>
  )
}
