"use client"
import './globals.css'
import type { Metadata } from 'next'

import {AppShell, Navbar, Header, createStyles, MantineProvider } from '@mantine/core';

const useStyles = createStyles((theme) => ({
  blackbg: {
    backgroundColor: "black"
  },
}));

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const { classes } = useStyles();
  return (
    <html lang="en">
      <MantineProvider withGlobalStyles withNormalizeCSS>
        <body className={classes.blackbg}>
          <AppShell 
          padding="md"
          navbar={<Navbar className={classes.blackbg} width={{ base: 300 }} p="xs">{/* Navbar content */}</Navbar>}
          header={<Header className={classes.blackbg} height={60} p="xs">{/* Header content */}</Header>}
          styles={()=>(
          {
           main:{ backgroudColor: "black"}
          })}
          >
            {children}
          </AppShell>
        </body>
      </MantineProvider>
    </html>
  )
}
